name: Build and Deploy
on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Use a version compatible with your project

      - name: Install dependencies
        run: npm install # Install Parcel and other dependencies

      - name: Build with Parcel
        run: npx parcel build index.html --dist-dir dist # Build your project into "dist"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Deploy the contents of "dist" to gh-pages
